/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControlDeEstudioVaney;

import java.awt.BorderLayout;
import javax.swing.JList;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
  
/**
 *
 * @author pc
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal2
     */
    
    public VentanaPrincipal() {
        
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Usuarios = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        jtxfCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCONSULTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Usuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Estudiante", "Profesor" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuariosMouseClicked(evt);
            }
        });
        Usuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                UsuariosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(Usuarios);

        jLabel1.setText("Seleccione que tipo de usuario desea consultar:");

        jLabel2.setText("Profesor/Estudiante:");

        jLabel3.setText("Código de Usuario:");

        Ingresar.setText("Ingresar");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingresar)
                            .addComponent(jtxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Ingresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );

        jTextAreaCONSULTA.setColumns(20);
        jTextAreaCONSULTA.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCONSULTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(221, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        String codigoB="";
        codigoB=jtxfCodigo.getText().toString();
        cargarDriver();
        if(!tipo.isEmpty()){
            if(tipo.equals("Estudiante")){
              
              try {
	          Connection conexion;
                  conexion = DriverManager.getConnection("jdbc:mysql://localhost/controldeestudio","root" ,"");
	          Statement comando= (Statement) conexion.createStatement();
	          ResultSet resultado = ((java.sql.Statement) comando).executeQuery("SELECT notas,NumeroSemestre, codigoMateria, codigoProfesor, codigoEstudiante FROM nota WHERE codigoEstudiante='"+codigoB+"'");
                  if(resultado.next()){
                     jTextAreaCONSULTA.append("Nota Final: "+resultado.getString("notas")+ "\n"+ 
                             "Semestre: "+resultado.getString("NumeroSemestre") + "\n"+
                             "Codigo de la Materia: "+resultado.getString("codigoMateria") + "\n"+
                             "Codigo del Profesor: " +resultado.getString("codigoProfesor") + "\n"+
                             "Codigo del Estudiante: " + resultado.getString("codigoEstudiante") + "\n"
                             );
                  }else{
                     System.out.println("No se consiguió el estudiante en la BD");
                  }  
                  conexion.close();
            
            }catch (SQLException ex){
	          setTitle(ex.toString());}
                      
            } else if (tipo.equals("Profesor")){
                
                 try {
	          Connection conexion;
                  conexion = DriverManager.getConnection("jdbc:mysql://localhost/controldeestudio","root" ,"");
	          Statement comando= (Statement) conexion.createStatement();
	          ResultSet resultado = ((java.sql.Statement) comando).executeQuery("SELECT nombre, apellido, edad, sexo, fecha_nacimiento, carrera, codigo, materias, titulo FROM profesor WHERE codigo='"+codigoB+"'");
                  if(resultado.next()){
                     jTextAreaCONSULTA.append("Datos Principales:\n Nombre: "+resultado.getString("nombre")+ "\n"+ 
                             "Apellido: "+resultado.getString("apellido") + "\n"+
                             "Edad: "+resultado.getString("edad") + "\n"+
                             "Sexo: " +resultado.getString("sexo") + "\n"+
                             "Fecha de Nacimiento: " + resultado.getString("fecha_nacimiento") + "\n" +
                             "Carrera: "+resultado.getString("carrera") +"\n"+
                             "Codigo: " +resultado.getString("codigo")+"\n"+
                             "Materias: "+resultado.getString("materias") + "\n"+
                             "Titulo: " +resultado.getString("titulo") + "\n"
                             );
                  }else{
                     System.out.println("No se consiguió el profesor en la BD");
                  }  
                  conexion.close();
            }catch (SQLException ex){
	          setTitle(ex.toString());}    
        
            }
           
        }else{
          
            
            System.out.println("Seleccione el tipo de usuario que quiere consultar");
            
        
        }    
        
    }//GEN-LAST:event_IngresarActionPerformed

    private void UsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_UsuariosValueChanged

    }//GEN-LAST:event_UsuariosValueChanged

    private void UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseClicked
        // TODO add your handling code here:
        tipo=Usuarios.getSelectedValue();
    }//GEN-LAST:event_UsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
    //metodos para la base de datos:
    private void cargarDriver() {
        try {
          Class.forName("com.mysql.jdbc.Driver");
        }catch(Exception ex) {
            System.out.println("hola");
          setTitle(ex.toString());
	}
    }
    
    

    private String tipo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JList<String> Usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaCONSULTA;
    private javax.swing.JTextField jtxfCodigo;
    // End of variables declaration//GEN-END:variables
}
